// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAEM5MgWJrwf6LGfJFUUjBFPMinbWpyhiA',
    appId: '1:822038010699:web:6ce7e1764c89caca8da6ce',
    messagingSenderId: '822038010699',
    projectId: 'store-app-adef4',
    authDomain: 'store-app-adef4.firebaseapp.com',
    storageBucket: 'store-app-adef4.firebasestorage.app',
    measurementId: 'G-N95JG7HPXJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuW1OSQo-B5DqeJxGFMr0m6OPK7xNf5Ns',
    appId: '1:822038010699:android:2677ba161a7e2cea8da6ce',
    messagingSenderId: '822038010699',
    projectId: 'store-app-adef4',
    storageBucket: 'store-app-adef4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDw7qkYwZ11FUwhR8fUnA0Pullqcp6JKNc',
    appId: '1:822038010699:ios:bb2e3f2dee6746178da6ce',
    messagingSenderId: '822038010699',
    projectId: 'store-app-adef4',
    storageBucket: 'store-app-adef4.firebasestorage.app',
    iosBundleId: 'com.example.storeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDw7qkYwZ11FUwhR8fUnA0Pullqcp6JKNc',
    appId: '1:822038010699:ios:bb2e3f2dee6746178da6ce',
    messagingSenderId: '822038010699',
    projectId: 'store-app-adef4',
    storageBucket: 'store-app-adef4.firebasestorage.app',
    iosBundleId: 'com.example.storeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAEM5MgWJrwf6LGfJFUUjBFPMinbWpyhiA',
    appId: '1:822038010699:web:948a86e0eb0c80328da6ce',
    messagingSenderId: '822038010699',
    projectId: 'store-app-adef4',
    authDomain: 'store-app-adef4.firebaseapp.com',
    storageBucket: 'store-app-adef4.firebasestorage.app',
    measurementId: 'G-G9RGZKC3XM',
  );
}
